"""CPGQL query templates and constructors.

The slice-construction algorithm in §3.2 of the paper composes three CPGQL
queries in sequence:

  1. The execution-path query (generated by LLMxCPG-Q at inference time).
  2. The interacters query (Listing 2): every identifier whose line number
     coincides with a node on the execution path.
  3. The backward slice query (Listing 3): everything reachable to the
     union of the execution path and its interacters via PDG flows.

We also expose a fourth helper that extracts the line numbers of every
node returned by step 3, so we can rebuild a contiguous code snippet from
the original source file.
"""

from __future__ import annotations


# ---------------------------------------------------------------------------
# Step 2: Interacters (Listing 2)
# ---------------------------------------------------------------------------
INTERACTERS_QUERY_TEMPLATE = """\
{execution_path_binding}

val execution_path_lines = execution_path.flatMap(_.elements).lineNumber.l.toSet
val interacters = cpg.identifier
    .filter(id => id.lineNumber.l.toSet.intersect(execution_path_lines).size >= 1)
    .l
"""


def build_interacters_query(execution_path_binding: str) -> str:
    """Compose the interacters query.

    Args:
        execution_path_binding: a Scala statement that binds `execution_path`
            to the result of the LLMxCPG-Q-generated taint flow query, e.g.
            `val execution_path = sink.reachableByFlows(source).l`.
    """
    if "execution_path" not in execution_path_binding:
        raise ValueError(
            "execution_path_binding must define `execution_path`. Got:\n"
            + execution_path_binding
        )
    return INTERACTERS_QUERY_TEMPLATE.format(
        execution_path_binding=execution_path_binding.rstrip()
    )


# ---------------------------------------------------------------------------
# Step 3: Backward slicing (Listing 3)
# ---------------------------------------------------------------------------
#
# `reachableByFlows(cpg.all)` is the paper's exact expression. Internally Joern
# uses the PDG to find every node that can flow to any element of the union of
# execution path nodes and interacters.
#
BACKWARD_SLICE_QUERY_TEMPLATE = """\
val all_path_nodes = execution_path.flatMap(_.elements).l ++ interacters
val slice = all_path_nodes.reachableByFlows(cpg.all).l
val slice_lines = slice.flatMap(_.elements).lineNumber.l.toSet.toList.sorted
slice_lines
"""


def build_backward_slice_query() -> str:
    """The final slice query. Assumes `execution_path` and `interacters` are
    already bound from the previous queries (run within the same session)."""
    return BACKWARD_SLICE_QUERY_TEMPLATE


# ---------------------------------------------------------------------------
# A safer drop-in: per-method scoping
# ---------------------------------------------------------------------------
#
# When the user-supplied taint-flow query forgets to constrain itself to a
# method, slicing can balloon. This helper wraps it.
#
def scope_to_method(query: str, method_name: str) -> str:
    """Restrict a top-level `cpg.X` traversal to a named method."""
    return query.replace("cpg.", f'cpg.method.name("{method_name}").', 1)


# ---------------------------------------------------------------------------
# Joern-scan style: validity probes used by the bootstrap loop
# ---------------------------------------------------------------------------
SYNTAX_PROBE = "1+1"  # cheap query to confirm the session is alive


# Hint phrases the bootstrap loop greps for when DeepSeek emits malformed CPGQL.
COMMON_SYNTAX_ERRORS = (
    "error: not found:",
    "error: value",
    "error: type mismatch",
    "error: missing argument",
    "Compilation failed",
)
